// ترجمة الواجهة للإنجليزية. المفتاح هو النص العربي كما هو في الكود.
// ignore_for_file: prefer_single_quotes
const Map<String, String> enStrings = {
  'الملف ليس نسخة احتياطية من هذا التطبيق': 'This file is not a backup of this app',
  'الفاتورة ملغاة': 'The invoice is void',
  'اكتب مبلغاً صحيحاً': 'Enter a valid amount',
  'المبلغ أكبر من المتبقي ({b})': 'The amount is more than the balance ({b})',
  'المبلغ أكبر من المستحق ({b})': 'The amount is more than what is due ({b})',
  'ليست لديك صلاحية الاسترداد': 'You don\'t have permission to refund',
  'مبلغ الاسترداد غير صحيح': 'Invalid refund amount',
  'استرداد: {r}': 'Refund: {r}',
  'ليست لديك صلاحية إلغاء الفواتير': 'You don\'t have permission to void invoices',
  'استرد المبلغ المدفوع أولاً ثم ألغِ الفاتورة': 'Refund the paid amount first, then void the invoice',
  'السلة فارغة': 'The cart is empty',
  'الكمية غير متوفرة من {p} (المتوفر {q})': 'Not enough {p} in stock (available {q})',
  'المبلغ المدفوع أكبر من الإجمالي': 'The paid amount is more than the total',
  'البيع بالآجل يحتاج اختيار عضو': 'Selling on credit requires choosing a member',
  'ليست لديك صلاحية المصروفات': 'You don\'t have permission for expenses',
  'السيدات': 'women',
  'الرجال': 'men',
  'البطاقة غير معروفة': 'Unknown card',
  'العضوية مؤرشفة': 'Membership is archived',
  'لا يوجد اشتراك': 'No membership',
  'الاشتراك يبدأ في {d}': 'Membership starts on {d}',
  'الاشتراك مجمّد حتى {d}': 'Membership is frozen until {d}',
  'انتهت الحصص ({n} من {t})': 'No sessions left ({n} of {t})',
  'انتهى الاشتراك منذ {n} يوم (فترة سماح)': 'Expired {n} days ago (grace period)',
  'انتهى الاشتراك في {d}': 'Membership expired on {d}',
  'الاشتراك ملغي': 'Membership cancelled',
  'الوقت الآن مخصص لـ {g} ({r})': 'This time is reserved for {g} ({r})',
  'أوقات {g}: {t}': 'Hours for {g}: {t}',
  'الباقة لا تناسب هذا العضو': 'The plan does not fit this member',
  'الباقة لا تسمح بالدخول اليوم': 'The plan does not allow entry today',
  'الباقة تسمح بالدخول من {f} إلى {t}': 'The plan allows entry from {f} to {t}',
  'دخل اليوم بالفعل': 'Already checked in today',
  'عليه مبلغ متأخر {a}': 'Overdue amount {a}',
  'عليه أقساط قادمة {a}': 'Upcoming installments {a}',
  'اليوم آخر يوم في الاشتراك': 'Today is the last day of the membership',
  'ينتهي الاشتراك بعد {n} يوم': 'Membership ends in {n} days',
  'تبقى {n} حصة بعد هذه': '{n} sessions left after this one',
  'أول زيارة — رحّب به!': 'First visit — welcome them!',
  'عيد ميلاده اليوم 🎂': 'Birthday today 🎂',
  'أهلاً {n}': 'Welcome {n}',
  'يحتاج صلاحية المدير': 'Requires manager permission',
  'ليست باقة تدريب شخصي': 'Not a personal training plan',
  'باقة التدريب غير فعالة': 'The training package is not active',
  'الحصة بدأت أو انتهت': 'The class has started or ended',
  'الحصة غير مخصصة لهذا العضو': 'This class is not for this member',
  'الحصة للأعضاء ذوي الاشتراك الفعّال فقط': 'This class is for active members only',
  'العضو محجوز في هذه الحصة': 'The member is already booked in this class',
  'ملف غير صالح': 'Invalid file',
  'الملف فارغ': 'The file is empty',
  'يجب أن يحتوي الصف الأول على عمودي الاسم والجوال': 'The first row must contain the name and phone columns',
  'صف {n}: الرقم مكرر ({p})': 'Row {n}: duplicate phone ({p})',
  'اشتراك مستورد': 'Imported membership',
  'رصيد سابق': 'Previous balance',
  'اكتب اسم العضو': 'Enter the member\'s name',
  'رقم الجوال مسجل للعضو {name} (رقم {code})': 'This phone number belongs to {name} (#{code})',
  'الباقة غير موجودة': 'Plan not found',
  'كوبون الخصم غير صالح': 'Invalid coupon',
  'العضو غير موجود': 'Member not found',
  'هذه الباقة مخصصة لـ {g} فقط': 'This plan is for {g} only',
  'اختر المدرب للتدريب الشخصي': 'Choose the trainer for personal training',
  'الخصم أعلى من المسموح ({p}%). يحتاج موافقة المدير': 'The discount is above the allowed limit ({p}%). Manager approval needed',
  'مجموع الأقساط والمدفوع الآن يجب أن يساوي الإجمالي ({t})': 'Installments plus the amount paid now must equal the total ({t})',
  'رسوم التسجيل': 'Registration fee',
  'عدد أيام التجميد غير صحيح': 'Invalid number of freeze days',
  'لا يمكن التجميد بتاريخ سابق': 'Cannot freeze on a past date',
  'تاريخ التجميد بعد نهاية الاشتراك': 'The freeze date is after the membership ends',
  'يتداخل مع تجميد آخر': 'Overlaps with another freeze',
  'تجاوز المسموح: متبقي {d} يوم و{t} مرة. يحتاج موافقة المدير': 'Over the allowance: {d} days and {t} times left. Manager approval needed',
  'لا يوجد تجميد حالي': 'No current freeze',
  'ليست لديك صلاحية الإلغاء والاسترداد': 'You don\'t have permission to cancel and refund',
  'الاسترداد أكبر من المدفوع': 'The refund is more than what was paid',
  'إلغاء اشتراك: {r}': 'Membership cancelled: {r}',
  'رابط المزوّد غير مضبوط': 'The provider URL is not set',
  'الإرسال من الشريحة متاح على أندرويد فقط': 'Sending from the SIM is available on Android only',
  'رقم غير صحيح': 'Invalid number',
  'طريقة الإرسال يدوية؛ لا يوجد مزوّد آلي لاختباره': 'Sending is manual; there is no automatic provider to test',
  'رسالة تجربة من {g} ✅': 'Test message from {g} ✅',
  'فاتورة': 'Invoice',
  'اكتب رابط الدفع في الإعدادات': 'Enter the payment link in settings',
  'فعّل بوابة الدفع من الإعدادات أولاً': 'Enable a payment gateway in settings first',
  'لا يوجد مبلغ مستحق': 'Nothing is due',
  'الرابط ليس معلّقاً': 'The link is not pending',
  'فاتورة ضريبية مبسطة': 'Simplified tax invoice',
  'الرقم الضريبي': 'VAT number',
  'التاريخ': 'Date',
  'العضو': 'Member',
  'العميل': 'Customer',
  'الجوال': 'Phone',
  'الحالة': 'Status',
  'ملغاة': 'Void',
  'البند': 'Item',
  'الكمية': 'Qty',
  'السعر': 'Price',
  'الإجمالي': 'Total',
  'المجموع': 'Subtotal',
  'الخصم': 'Discount',
  'الضريبة': 'Tax',
  'شاملة': 'inclusive',
  'المدفوع': 'Paid',
  'المتبقي': 'Balance',
  'جدول الأقساط': 'Installment schedule',
  'الدفعات': 'Payments',
  'امسح للدفع': 'Scan to pay',
  'تقرير الفترة': 'Period report',
  'المحصّل': 'Collected',
  'المبيعات (قيمة الفواتير)': 'Sales (invoice value)',
  'المصروفات': 'Expenses',
  'صافي الربح النقدي': 'Net cash profit',
  'أعضاء جدد': 'New members',
  'اشتراكات جديدة / تجديد': 'New / renewed memberships',
  'نسبة التجديد': 'Renewal rate',
  'الزيارات': 'Visits',
  'الأعضاء الفعّالون اليوم': 'Active members today',
  'صاحب النادي': 'Gym owner',
  'فاتورة رقم {n}': 'Invoice #{n}',
  'الخصم: {a}': 'Discount: {a}',
  'الضريبة: {a}': 'Tax: {a}',
  'الإجمالي: {a}': 'Total: {a}',
  'المدفوع: {a}': 'Paid: {a}',
  'المتبقي: {a}': 'Balance: {a}',
  '💰 المحصّل: {a}': '💰 Collected: {a}',
  '📉 المصروفات: {a}': '📉 Expenses: {a}',
  '🆕 اشتراكات جديدة: {n} — تجديد: {r}': '🆕 New memberships: {n} — renewals: {r}',
  '🚶 الزيارات: {n}': '🚶 Visits: {n}',
  '⏳ تنتهي خلال 7 أيام: {n}': '⏳ Expiring within 7 days: {n}',
  '👥 الأعضاء الفعّالون: {n}': '👥 Active members: {n}',
  'نقداً': 'Cash',
  'بطاقة': 'Card',
  'تحويل بنكي': 'Bank transfer',
  'محفظة إلكترونية': 'E-wallet',
  'دفع أونلاين': 'Online payment',
  'اشتراكات': 'Memberships',
  'رسوم تسجيل': 'Registration fees',
  'تدريب شخصي': 'Personal training',
  'المتجر': 'Shop',
  'خزائن': 'Lockers',
  'حصص': 'Classes',
  'أخرى': 'Other',
  'تم الإرسال ✓': 'Sent ✓',
  'تعذر الإرسال': 'Could not send',
  'تعذر فتح التطبيق': 'Could not open the app',
  'فُتح واتساب — اضغط إرسال': 'WhatsApp opened — tap send',
  'فُتحت الرسائل — اضغط إرسال': 'Messages opened — tap send',
  'الفاتورة ليست لعضو': 'The invoice is not for a member',
  'خصم': 'Discount',
  'استرداد': 'Refund',
  'إلغاء فاتورة': 'Invoice voided',
  'إلغاء اشتراك': 'Membership cancelled',
  'تجميد': 'Freeze',
  'فك تجميد': 'Unfreeze',
  'سماح استثنائي': 'Override',
  'تعديل يدوي': 'Manual adjustment',
  'تغيير سعر': 'Price change',
  'حذف عضو': 'Member deleted',
  'مكافأة ترشيح': 'Referral reward',
  'رسالة جماعية': 'Bulk message',
  'موظفون': 'Staff',
  'مخزون': 'Stock',
  'حذف مصروف': 'Expense deleted',
  'سجل العمليات': 'Activity log',
  'لا توجد عمليات مسجلة': 'No activity recorded',
  'سماح استثنائي بالدخول؟': 'Allow entry as an exception?',
  'سماح': 'Allow',
  'سُجل الدخول استثنائياً': 'Entry recorded as an exception',
  'تسجيل الدخول': 'Check-in',
  'في النادي: {n}': 'In gym: {n}',
  'شاشة الدخول الذاتي': 'Self check-in screen',
  'امسح البطاقة أو اكتب الاسم / الجوال / الرقم': 'Scan the card or type the name / phone / number',
  'الكاميرا': 'Camera',
  'تعذر تشغيل الكاميرا': 'Could not start the camera',
  'اطلب من العضو عرض بطاقته (QR) أو اكتب اسمه': 'Ask the member to show their QR card or type their name',
  'يعمل أيضاً مع قارئ الباركود الموصول بالجهاز': 'Also works with a barcode scanner connected to the device',
  'زيارات اليوم ({n})': 'Today\'s visits ({n})',
  'لا زيارات بعد': 'No visits yet',
  'مسموح': 'Allowed',
  'مرفوض': 'Denied',
  '{n} حصة متبقية': '{n} sessions left',
  'ينتهي {d}': 'Ends {d}',
  'عليه {a}': 'Owes {a}',
  'تجديد': 'Renew',
  'تحصيل': 'Collect',
  'الملف': 'Profile',
  'سُجّل الدخول {t}': 'Checked in at {t}',
  'الحصص والحجوزات': 'Classes & bookings',
  'إدارة الحصص': 'Manage classes',
  'لا توجد حصص بعد': 'No classes yet',
  'لا حصص في هذا اليوم': 'No classes on this day',
  'إضافة حصة': 'Add a class',
  'د': 'min',
  '+{n} انتظار': '+{n} waiting',
  'الحصة ممتلئة — أُضيف لقائمة الانتظار': 'The class is full — added to the waitlist',
  'تم الحجز ✓': 'Booked ✓',
  'حجز لعضو': 'Book a member',
  'لا حجوزات': 'No bookings',
  'محجوز': 'Booked',
  'قائمة الانتظار': 'Waitlist',
  'حضر ✓': 'Attended ✓',
  'لم يحضر': 'No-show',
  'ملغي': 'Cancelled',
  'حضر': 'Attended',
  'إلغاء الحجز': 'Cancel booking',
  'انتقل {n} من الانتظار إلى الحجز': '{n} moved from the waitlist to booked',
  'موقوفة': 'Paused',
  'حصة جديدة': 'New class',
  'تعديل الحصة': 'Edit class',
  'حذف الحصة؟': 'Delete this class?',
  'حذف': 'Delete',
  'حفظ': 'Save',
  'اسم الحصة': 'Class name',
  'السعة': 'Capacity',
  'المدة (دقيقة)': 'Duration (minutes)',
  'القاعة': 'Room',
  'المدرب': 'Trainer',
  'بدون': 'None',
  'الجميع': 'Everyone',
  'رجال': 'Men',
  'سيدات': 'Women',
  'للمشتركين فقط': 'Members only',
  'فعّالة': 'Active',
  'المواعيد الأسبوعية': 'Weekly schedule',
  'اليوم': 'Today',
  'موعد': 'Time slot',
  'صباح الخير': 'Good morning',
  'مساء الخير': 'Good evening',
  'الرسائل': 'Messages',
  'تبديل المستخدم': 'Switch user',
  'عضو جديد': 'New member',
  'أعضاء فعّالون': 'Active members',
  '{n} ينتهي قريباً': '{n} expiring soon',
  'في النادي الآن': 'In the gym now',
  '{n} زيارة اليوم': '{n} visits today',
  'تحصيل اليوم': 'Collected today',
  'الشهر': 'Month',
  'ينتهي خلال 7 أيام': 'Expiring within 7 days',
  'ديون مستحقة': 'Outstanding debts',
  '{n} عضو': '{n} members',
  'منتهي الاشتراك': 'Expired',
  'فرص للاسترجاع': 'Win-back opportunities',
  'إجراءات سريعة': 'Quick actions',
  'تسجيل دخول': 'Check in',
  'عملاء محتملون': 'Leads',
  'يحتاج انتباهك': 'Needs your attention',
  '{n} رسالة تذكير جاهزة للإرسال': '{n} reminders ready to send',
  'أرسلها بلمسة من واتساب أو الرسائل': 'Send them with one tap via WhatsApp or SMS',
  '{n} قسط مستحق أو متأخر': '{n} installments due or overdue',
  'عيد ميلاد {n} اليوم 🎂': '{n}\'s birthday today 🎂',
  '{n} متابعة لعملاء محتملين': '{n} lead follow-ups',
  '{n} منتج قارب على النفاد': '{n} products running low',
  'التحصيل آخر 14 يوماً': 'Collections, last 14 days',
  'التقارير': 'Reports',
  'تنتهي اشتراكاتهم قريباً': 'Memberships ending soon',
  'الكل': 'All',
  'آخر الزيارات اليوم': 'Latest visits today',
  'دخل': 'Entered',
  'غير معروف': 'Unknown',
  'مؤرشف': 'Archived',
  'بدون اشتراك': 'No membership',
  'منتهي': 'Expired',
  'انتهت الحصص': 'No sessions left',
  'مجمّد': 'Frozen',
  'لم يبدأ': 'Not started',
  'خارج ساعات الباقة': 'Outside plan hours',
  'يوم غير مسموح': 'Day not allowed',
  'خارج أوقاته': 'Outside their hours',
  'باقة غير مناسبة': 'Plan not suitable',
  'دخل اليوم': 'Already in today',
  'مديونية': 'Debt',
  'المالية': 'Finance',
  'الفواتير': 'Invoices',
  'الأقساط': 'Installments',
  'المدينون': 'Debtors',
  'مدفوعة': 'Paid',
  'جزئي': 'Partial',
  'غير مدفوعة': 'Unpaid',
  'زائر': 'Walk-in',
  'مقسطة': 'Installments',
  'باقي': 'Left',
  'رقم الفاتورة أو اسم العضو': 'Invoice number or member name',
  'غير مسددة': 'Unpaid',
  'هذا الشهر': 'This month',
  '{n} فاتورة': '{n} invoices',
  'غير مسدد': 'Unpaid',
  'لا توجد فواتير': 'No invoices',
  'لا توجد أقساط مستحقة': 'No installments due',
  'متأخر': 'Overdue',
  'قادم': 'Upcoming',
  'لا توجد ديون 👏': 'No debts 👏',
  'إجمالي الديون {a} على {n} عضو': 'Total debts {a} across {n} members',
  'متأخر {a}': 'Overdue {a}',
  'أقساط قادمة': 'Upcoming installments',
  'تذكير': 'Remind',
  'مرحباً {n}، نذكّرك بمبلغ {a} مستحق لدى {g}. شكراً لك 🙏': 'Hi {n}, a reminder that {a} is due at {g}. Thank you 🙏',
  'مصروف': 'Expense',
  'لا توجد مصروفات': 'No expenses',
  'سجّل الإيجار والرواتب والفواتير لتعرف ربحك الحقيقي': 'Record rent, salaries and bills to see your real profit',
  'مصروفات هذا الشهر: {a}': 'Expenses this month: {a}',
  'حذف المصروف؟': 'Delete this expense?',
  'مصروف جديد': 'New expense',
  'المبلغ': 'Amount',
  'ملاحظة': 'Note',
  'إلغاء': 'Cancel',
  'تم الحفظ': 'Saved',
  'الفاتورة غير موجودة': 'Invoice not found',
  'مدفوعة بالكامل': 'Fully paid',
  'مدفوعة جزئياً': 'Partially paid',
  'طباعة': 'Print',
  'مشاركة PDF': 'Share PDF',
  'استرداد مبلغ': 'Refund an amount',
  'إلغاء الفاتورة': 'Void invoice',
  'نسخ نص الفاتورة': 'Copy invoice text',
  'إرسال': 'Send',
  'سبب الإلغاء': 'Void reason',
  'دُفع {a}': 'Paid {a}',
  'لا توجد دفعات': 'No payments',
  'ورق A4': 'A4 paper',
  'إيصال حراري 80مم': '80mm thermal receipt',
  'إرسال الفاتورة': 'Send invoice',
  'رسالة واتساب (نص الفاتورة)': 'WhatsApp message (invoice text)',
  'رسالة SMS': 'SMS message',
  'ملف PDF (اختر واتساب من قائمة المشاركة)': 'PDF file (choose WhatsApp from the share menu)',
  'مبلغ الاسترداد': 'Refund amount',
  'سبب الاسترداد': 'Refund reason',
  'تم الاسترداد': 'Refunded',
  'سبب إلغاء الفاتورة': 'Reason for voiding the invoice',
  'أُلغيت الفاتورة': 'Invoice voided',
  'نُسخ النص': 'Text copied',
  'الدفع الإلكتروني': 'Online payment',
  'تم التحقق': 'Checked',
  'تحقق من الدفع': 'Check payment',
  'سُجّل الدفع': 'Payment recorded',
  'نسخ الرابط': 'Copy link',
  'تأكيد استلام الدفع يدوياً': 'Confirm payment received manually',
  'إلغاء الرابط': 'Cancel link',
  'مدفوع': 'Paid',
  'نُسخ الرابط': 'Link copied',
  'إنشاء رابط دفع وإرساله للعضو': 'Create a payment link and send it to the member',
  'فعّل بوابة دفع من الإعدادات (Stripe، ميسّر، Tap أو رابط انستاباي/محفظة) ليدفع العضو من جواله': 'Enable a payment gateway in settings (Stripe, Moyasar, Tap or an InstaPay/wallet link) so members can pay from their phone',
  'امسح بطاقتك للدخول': 'Scan your card to enter',
  'الكاميرا غير متاحة — استخدم قارئ الباركود': 'Camera unavailable — use the barcode scanner',
  'جديد': 'New',
  'تم التواصل': 'Contacted',
  'حصة تجربة': 'Trial session',
  'اشترك': 'Joined',
  'لم يشترك': 'Did not join',
  'العملاء المحتملون': 'Leads',
  'عميل محتمل': 'Lead',
  'نسبة التحويل: {p}% ({w} من {c})': 'Conversion rate: {p}% ({w} of {c})',
  'قيد المتابعة': 'In follow-up',
  'لا يوجد': 'Nothing here',
  'سجّل كل من يسأل عن الأسعار وتابعه بالواتساب حتى يشترك': 'Record everyone who asks about prices and follow up on WhatsApp until they join',
  'متابعة': 'Follow-up',
  'مرحباً {n} 👋 معك {g}': 'Hi {n} 👋 this is {g}',
  'الاسم': 'Name',
  'مهتم بباقة': 'Interested in plan',
  'غير محدد': 'Not specified',
  'المصدر': 'Source',
  'موعد المتابعة': 'Follow-up date',
  'ملاحظات': 'Notes',
  'تحويل لعضو': 'Convert to member',
  'المالك': 'Owner',
  'مدير': 'Manager',
  'استقبال': 'Reception',
  'مدرب': 'Trainer',
  'من يستخدم التطبيق؟': 'Who is using the app?',
  'رقم سري خاطئ': 'Wrong PIN',
  'أدخل الرقم السري': 'Enter your PIN',
  'بطاقة عضويتك في {g} — اعرضها عند الدخول': 'Your {g} membership card — show it at the entrance',
  'حتى': 'until',
  'يمسح موظف الاستقبال الرمز من شاشة «الدخول»': 'Reception scans the code from the Check-in screen',
  'مشاركة': 'Share',
  'إغلاق': 'Close',
  'تعديل': 'Edit',
  'تجميد الاشتراك': 'Freeze membership',
  'إنهاء التجميد': 'End freeze',
  'تعديل تاريخ الانتهاء': 'Change end date',
  'إلغاء الاشتراك واسترداد': 'Cancel membership & refund',
  'فاتورة يدوية': 'Manual invoice',
  'إضافة قياسات': 'Add measurements',
  'إلغاء الأرشفة': 'Unarchive',
  'أرشفة العضو': 'Archive member',
  'حذف نهائي': 'Delete permanently',
  'عيد ميلاده 🎂': 'Birthday 🎂',
  'أوقف الرسائل': 'Opted out of messages',
  'المستحق عليه: {a}': 'Owes: {a}',
  'متأخر: {a}': 'Overdue: {a}',
  'متبقي {n} من {t}': '{n} of {t} left',
  'سُجلت الجلسة ✓': 'Session recorded ✓',
  'جلسة': 'Session',
  'اشتراك': 'Subscribe',
  'دخول': 'Check in',
  'واتساب': 'WhatsApp',
  'اتصال': 'Call',
  'البطاقة': 'Card',
  'الاشتراكات': 'Memberships',
  'الحضور': 'Attendance',
  'القياسات': 'Measurements',
  'الدخول مرفوض': 'Entry denied',
  'حسناً': 'OK',
  'إنهاء التجميد اليوم؟': 'End the freeze today?',
  'تُعاد الأيام غير المستخدمة للاشتراك': 'Unused days are returned to the membership',
  'انتهى التجميد': 'Freeze ended',
  'سبب التعديل': 'Reason for the change',
  'تعويض، خطأ إدخال...': 'Compensation, data entry error...',
  'تم التعديل': 'Updated',
  'حذف {n} نهائياً؟': 'Permanently delete {n}?',
  'ستُحذف بيانات العضو وسجل حضوره. الفواتير تبقى في الحسابات. الأفضل استخدام الأرشفة.': 'The member\'s data and attendance will be deleted. Invoices stay in the accounts. Archiving is usually better.',
  'المتبقي من حق التجميد: {d} يوم و{t} مرة': 'Freeze allowance left: {d} days and {t} times',
  'من تاريخ': 'From date',
  'عدد الأيام': 'Number of days',
  'السبب (سفر، مرض...)': 'Reason (travel, illness...)',
  'تم التجميد، ومُدّد الاشتراك': 'Frozen, and the membership was extended',
  'إلغاء الاشتراك': 'Cancel membership',
  'المدفوع في هذا الاشتراك: {a}': 'Paid for this membership: {a}',
  'المبلغ المسترد': 'Refunded amount',
  'السبب': 'Reason',
  'رجوع': 'Back',
  'بدون سبب': 'No reason',
  'أُلغي الاشتراك': 'Membership cancelled',
  'خزانة': 'Locker',
  'حصة': 'Class',
  'النوع': 'Type',
  'الوصف': 'Description',
  'مدفوعة نقداً الآن': 'Paid in cash now',
  'خدمة': 'Service',
  'اشترك الآن': 'Subscribe now',
  'آخر يوم': 'Last day',
  '{n} يوم متبقٍ': '{n} days left',
  'انتهى منذ {n} يوم': 'Ended {n} days ago',
  'تجميد متبقٍ: {n} يوم': 'Freeze left: {n} days',
  'مجمّد حتى {d}': 'Frozen until {d}',
  'مُجدَّد: {p} يبدأ {d}': 'Renewed: {p} starts {d}',
  'آخر زيارة: {d}': 'Last visit: {d}',
  'لا توجد اشتراكات': 'No memberships',
  'فعّال': 'Active',
  '{u} من {t} حصة': '{u} of {t} sessions',
  'جُمّد {n} يوم': 'Frozen {n} days',
  'مستورد': 'Imported',
  'لا توجد زيارات': 'No visits',
  '{n} زيارة في آخر 30 يوماً • الإجمالي {t}': '{n} visits in the last 30 days • {t} total',
  'لا توجد قياسات': 'No measurements',
  'سجّل الوزن ونسبة الدهون لمتابعة تقدّم العضو': 'Record weight and body fat to track the member\'s progress',
  'الوزن': 'Weight',
  'كجم': 'kg',
  'نسبة الدهون': 'Body fat',
  'مؤشر كتلة الجسم': 'BMI',
  'السجل': 'History',
  'إضافة': 'Add',
  'وزن': 'Weight',
  'دهون': 'Fat',
  'عضل': 'Muscle',
  'خصر': 'Waist',
  'الوزن (كجم)': 'Weight (kg)',
  'الطول (سم)': 'Height (cm)',
  'نسبة الدهون %': 'Body fat %',
  'الكتلة العضلية (كجم)': 'Muscle mass (kg)',
  'الخصر (سم)': 'Waist (cm)',
  'الصدر (سم)': 'Chest (cm)',
  'الذراع (سم)': 'Arm (cm)',
  'الورك (سم)': 'Hip (cm)',
  'الفخذ (سم)': 'Thigh (cm)',
  'قياسات {n}': '{n}\'s measurements',
  'رسالة جديدة': 'New message',
  'لا توجد رسائل': 'No messages',
  'في الانتظار': 'Waiting',
  'جاهزة للإرسال': 'Ready to send',
  'أُرسلت': 'Sent',
  'فشلت': 'Failed',
  'أُلغيت': 'Cancelled',
  'تعذر فتح الكاميرا': 'Could not open the camera',
  'تعديل بيانات العضو': 'Edit member',
  'حفظ ومتابعة للاشتراك': 'Save and continue to membership',
  'التقاط صورة': 'Take a photo',
  'من المعرض': 'From gallery',
  'حذف الصورة': 'Remove photo',
  'الاسم الكامل': 'Full name',
  'مطلوب': 'Required',
  'الجوال (واتساب)': 'Phone (WhatsApp)',
  'ذكر': 'Male',
  'أنثى': 'Female',
  'تاريخ الميلاد (لتهنئة عيد الميلاد)': 'Date of birth (for birthday greetings)',
  'كيف عرف النادي؟': 'How did they hear about the gym?',
  'رشّحه عضو': 'Referred by a member',
  'لا أحد': 'Nobody',
  'إيقاف رسائل التذكير والعروض': 'Stop reminder and offer messages',
  'تُرسل له الفواتير وتذكير الأقساط فقط': 'Only invoices and installment reminders will be sent',
  'ملاحظات صحية (تظهر عند الدخول)': 'Health notes (shown at check-in)',
  'بيانات إضافية': 'More details',
  'جوال آخر': 'Other phone',
  'البريد الإلكتروني': 'Email',
  'رقم الهوية': 'ID number',
  'العنوان': 'Address',
  'اسم شخص للطوارئ': 'Emergency contact name',
  'هاتف الطوارئ': 'Emergency phone',
  'ينتهي قريباً': 'Expiring soon',
  'عليه دين': 'Has debt',
  'اختر العضو للتجديد': 'Choose a member to renew',
  'اختر عضواً': 'Choose a member',
  'الأعضاء ({n})': 'Members ({n})',
  'الترتيب والتصفية': 'Sort and filter',
  'الأحدث': 'Newest',
  'تاريخ الانتهاء': 'End date',
  'رقم العضوية': 'Member number',
  'الرجال فقط': 'Men only',
  'السيدات فقط': 'Women only',
  'ابحث بالاسم أو الجوال أو رقم العضوية': 'Search by name, phone or member number',
  'لا يوجد أعضاء بعد': 'No members yet',
  'لا نتائج': 'No results',
  'أضف أول عضو أو استورد قائمتك من Excel من الإعدادات': 'Add your first member or import your list from Excel in settings',
  '{n} حصة': '{n} sessions',
  'انتهى': 'Ended',
  'يبدأ': 'Starts',
  'ترحيب': 'Welcome',
  'إيصال دفع': 'Payment receipt',
  'قرب الانتهاء': 'Expiring soon',
  'انتهاء الاشتراك': 'Membership expired',
  'استرجاع': 'Win-back',
  'حصص قليلة': 'Few sessions left',
  'قسط قادم': 'Upcoming installment',
  'قسط متأخر': 'Overdue installment',
  'عيد ميلاد': 'Birthday',
  'غياب': 'Absence',
  'نهاية التجميد': 'Freeze ending',
  'تذكير حصة': 'Class reminder',
  'ملخص للمالك': 'Owner summary',
  'حملة': 'Campaign',
  'رسالة': 'Message',
  'أُرسلت كل الرسائل ({n}) ✓': 'All messages sent ({n}) ✓',
  'الرسائل والتذكيرات': 'Messages & reminders',
  'فحص التذكيرات الآن': 'Check reminders now',
  '{n} تذكير جديد': '{n} new reminders',
  'إعدادات الرسائل': 'Message settings',
  'جاهزة': 'Ready',
  'آلية/فشلت': 'Automatic/failed',
  'المرسلة': 'Sent',
  'واتساب يُرسل آلياً عبر المزوّد. الرسائل هنا لأعضاء اختاروا SMS أو لتعذر الإرسال.': 'WhatsApp is sent automatically through the provider. Messages here are for members who chose SMS or could not be reached.',
  'التذكيرات تُجهّز تلقائياً كل يوم. اضغط «إرسال الكل» وسيفتح واتساب لكل عضو والرسالة جاهزة — اضغط إرسال ثم ارجع للتطبيق ليفتح التالي.': 'Reminders are prepared automatically every day. Tap "Send all" and WhatsApp opens for each member with the message ready — tap send, then return to the app to open the next one.',
  'فعّل الإرسال الآلي الكامل (بدون لمس)': 'Enable fully automatic sending (no taps)',
  'إيقاف الإرسال المتتالي': 'Stop sequential sending',
  'إرسال الكل ({n})': 'Send all ({n})',
  'لا رسائل تنتظر الإرسال': 'No messages waiting to be sent',
  'لا رسائل في الانتظار': 'No messages waiting',
  'أُرسلت {s} • فشلت {f}': 'Sent {s} • failed {f}',
  'أرسل الآن': 'Send now',
  'لم تُرسل رسائل بعد': 'No messages sent yet',
  'إرسال بـ SMS بدلاً من واتساب': 'Send by SMS instead of WhatsApp',
  'إرسال بواتساب بدلاً من SMS': 'Send by WhatsApp instead of SMS',
  'الأعضاء الفعّالون': 'Active members',
  'ينتهي اشتراكهم خلال 7 أيام': 'Membership ends within 7 days',
  'منتهي خلال آخر 60 يوماً': 'Expired in the last 60 days',
  'المجمّدون': 'Frozen members',
  'عليهم مبالغ': 'Members who owe money',
  'فعّالون لم يحضروا منذ 14 يوماً': 'Active but absent for 14 days',
  'السيدات الفعّالات': 'Active women',
  'الرجال الفعّالون': 'Active men',
  'أعياد ميلاد هذا الشهر': 'Birthdays this month',
  'كل الأعضاء': 'All members',
  'إرسال لـ {n} شخص؟': 'Send to {n} people?',
  'جُهّزت {n} رسالة': '{n} messages prepared',
  'إرسال إلى {n}': 'Send to {n}',
  'إلى من؟': 'To whom?',
  'باقة محددة (اختياري)': 'Specific plan (optional)',
  'كل الباقات': 'All plans',
  'الرسالة': 'Message',
  'حسب تفضيل العضو': 'Member\'s preference',
  'SMS': 'SMS',
  'معاينة': 'Preview',
  'الأعضاء الذين أوقفوا الرسائل لا يُرسل لهم.': 'Members who opted out will not receive it.',
  'الباقات والأسعار': 'Plans & prices',
  'المتجر والمخزون': 'Shop & stock',
  'الموظفون والمدربون': 'Staff & trainers',
  'الإعدادات': 'Settings',
  'المزيد': 'More',
  'خروج': 'Log out',
  'نادي اللياقة': 'Fitness Club',
  'شهري': 'Monthly',
  '3 أشهر': '3 months',
  '6 أشهر': '6 months',
  'سنوي': 'Yearly',
  '12 حصة': '12 sessions',
  'يوم واحد': 'One day',
  'جاهز! حدّد أسعار الباقات من «المزيد › الباقات»': 'Ready! Set your plan prices from More › Plans',
  'أهلاً بك في نادي جيم': 'Welcome to Nadi Gym',
  'إدارة الأعضاء والاشتراكات والدفع والتذكيرات بواتساب والرسائل — من جوالك وبدون إنترنت': 'Manage members, memberships, payments and WhatsApp & SMS reminders — from your phone, even offline',
  'اسم النادي': 'Gym name',
  'اسمك (المالك)': 'Your name (owner)',
  'الدولة والعملة': 'Country & currency',
  'هاتف النادي (للأعضاء)': 'Gym phone (for members)',
  'ابدأ': 'Start',
  'جرّب ببيانات نادٍ تجريبي': 'Try it with a demo gym',
  'بياناتك تُحفظ على هذا الجهاز فقط. خذ نسخة احتياطية من الإعدادات بانتظام.': 'Your data is stored on this device only. Take a backup from settings regularly.',
  'باقة': 'Plan',
  'لا توجد باقات': 'No plans',
  'بيعت {n} مرة': 'Sold {n} times',
  'اكتب اسم الباقة': 'Enter the plan name',
  'باقة جديدة': 'New plan',
  'تعديل الباقة': 'Edit plan',
  'اسم الباقة': 'Plan name',
  'مدة': 'Duration',
  'رسوم تسجيل (للجدد)': 'Registration fee (new members)',
  'المدة': 'Duration',
  'الصلاحية': 'Validity',
  'يوم': 'day',
  'أسبوع': 'week',
  'شهر': 'month',
  'سنة': 'year',
  'حد أقصى للزيارات (اتركه فارغاً = غير محدود)': 'Max visits (leave empty = unlimited)',
  'عدد الحصص/الجلسات': 'Number of sessions',
  'أيام التجميد المسموحة': 'Allowed freeze days',
  'مرات التجميد': 'Allowed freezes',
  'قيود الدخول': 'Access rules',
  'ساعات محددة (باقة صباحية/اقتصادية)': 'Specific hours (morning/off-peak plan)',
  'من': 'From',
  'إلى': 'To',
  'أيام الدخول (بدون اختيار = كل الأيام)': 'Entry days (none selected = every day)',
  'مرات الدخول في اليوم': 'Entries per day',
  'بلا حد': 'Unlimited',
  'اللون': 'Color',
  'وصف (اختياري)': 'Description (optional)',
  'الباقة متاحة للبيع': 'Available for sale',
  '7 أيام': '7 days',
  '30 يوماً': '30 days',
  'هذه السنة': 'This year',
  'فترة محددة': 'Custom range',
  'تقرير PDF': 'PDF report',
  'تصدير الدفعات CSV': 'Export payments CSV',
  'رقم الإيصال': 'Receipt no.',
  'الفاتورة': 'Invoice',
  'طريقة الدفع': 'Payment method',
  'المرجع': 'Reference',
  'الموظف': 'Staff',
  'صافي الربح': 'Net profit',
  'تجديد: {n}': 'Renewals: {n}',
  '{r} من {e} انتهى': '{r} of {e} ended',
  'متوسط {n}/يوم': 'Avg {n}/day',
  'التحصيل': 'Collections',
  'حسب طريقة الدفع': 'By payment method',
  'المبيعات حسب النوع': 'Sales by type',
  'منها ضريبة': 'Of which tax',
  'أوقات الذروة': 'Peak hours',
  '{n} زيارة': '{n} visits',
  'الزيارات حسب اليوم': 'Visits by day',
  'الباقات الأكثر مبيعاً': 'Best-selling plans',
  'المدربون': 'Trainers',
  'مبيعات تدريب {s} • {n} جلسة': 'PT sales {s} • {n} sessions',
  'مستحق': 'Due',
  'الأكثر حضوراً': 'Most frequent visitors',
  'دخول غير محدود': 'Unlimited entry',
  'اشتراك جديد': 'New membership',
  'تجديد الاشتراك': 'Renew membership',
  'اختر الباقة': 'Choose a plan',
  'تأكيد واستلام {a}': 'Confirm and receive {a}',
  'تأكيد بدون دفع (آجل)': 'Confirm without payment (on credit)',
  'ينتهي': 'Ends',
  'الباقة': 'Plan',
  'أضف الباقات من «المزيد › الباقات»': 'Add plans from More › Plans',
  'أضف المدربين من «المزيد › الموظفون والمدربون»': 'Add trainers from More › Staff & trainers',
  'يبدأ من': 'Starts on',
  'خصم (مبلغ)': 'Discount (amount)',
  'كوبون': 'Coupon',
  'خصم الكوبون': 'Coupon discount',
  '(شاملة)': '(inclusive)',
  '(تضاف)': '(added)',
  'الدفع': 'Payment',
  'المدفوع الآن': 'Paid now',
  'رقم العملية': 'Transaction no.',
  'تقسيط الباقي': 'Pay the rest in installments',
  'مع تذكير تلقائي قبل كل قسط': 'With an automatic reminder before each installment',
  'عدد الأقساط': 'Number of installments',
  'المتبقي {a} يُسجل ديناً على العضو': 'The remaining {a} is recorded as the member\'s debt',
  'تم بنجاح': 'Done',
  'أُرسل الإيصال للعضو تلقائياً ✓': 'Receipt sent to the member automatically ✓',
  'إرسال الفاتورة بواتساب': 'Send invoice via WhatsApp',
  'إرسال رسالة الترحيب': 'Send the welcome message',
  'PDF': 'PDF',
  'بطاقة العضو': 'Member card',
  'تم': 'Done',
  'النادي': 'Gym',
  'الاسم، الشعار، العملة، اللغة، المظهر': 'Name, logo, currency, language, appearance',
  'الفواتير والضريبة': 'Invoices & tax',
  'ضريبة القيمة المضافة، رمز QR، نص الفاتورة': 'VAT, QR code, invoice text',
  'قواعد الدخول': 'Access rules',
  'ساعات السيدات، فترة السماح، الديون': 'Women\'s hours, grace period, debts',
  'واتساب، SMS، القوالب، مواعيد التذكير': 'WhatsApp, SMS, templates, reminder timing',
  'روابط الدفع، المحافظ، البوابات': 'Payment links, wallets, gateways',
  'كوبونات الخصم': 'Discount coupons',
  'عروض ومواسم وخصومات': 'Offers, seasons and discounts',
  'الأمان': 'Security',
  'الرقم السري للموظفين': 'Staff PINs',
  'البيانات': 'Data',
  'نسخ احتياطي، استرجاع، استيراد من Excel': 'Backup, restore, import from Excel',
  'اللغة': 'Language',
  'الشعار (يظهر في الفواتير والبطاقات)': 'Logo (shown on invoices and cards)',
  'هاتف النادي': 'Gym phone',
  'اختر الدولة': 'Choose country',
  'رمز العملة الظاهر': 'Displayed currency symbol',
  'رمز الاتصال الدولي للدولة': 'Country calling code',
  'يُستخدم لتحويل أرقام الأعضاء المحلية (مثل 010...) إلى صيغة واتساب الدولية.': 'Used to convert members\' local numbers (e.g. 010...) to the international WhatsApp format.',
  'المظهر': 'Appearance',
  'تلقائي': 'Automatic',
  'فاتح': 'Light',
  'داكن': 'Dark',
  'التجديد والترشيح': 'Renewals & referrals',
  'التجديد يبدأ من نهاية الاشتراك الحالي': 'Renewal starts at the end of the current membership',
  'لا يخسر العضو أياماً عند التجديد المبكر': 'Members don\'t lose days when renewing early',
  'أيام مجانية لمن يرشّح عضواً جديداً': 'Free days for referring a new member',
  'أعلى خصم يمنحه موظف الاستقبال (%)': 'Maximum discount reception can give (%)',
  'تفعيل ضريبة القيمة المضافة': 'Enable VAT',
  'نسبة الضريبة %': 'VAT rate %',
  'الأسعار شاملة الضريبة': 'Prices include VAT',
  'رمز QR للفاتورة الضريبية (السعودية)': 'Tax invoice QR code (Saudi Arabia)',
  'صيغة هيئة الزكاة والضريبة للفواتير المبسطة': 'ZATCA format for simplified invoices',
  'شكل الفاتورة': 'Invoice layout',
  'بادئة رقم الفاتورة': 'Invoice number prefix',
  'نص أسفل الفاتورة': 'Invoice footer text',
  'الطباعة الافتراضية: إيصال حراري 80مم': 'Default printing: 80mm thermal receipt',
  'وإلا ورق A4': 'Otherwise A4 paper',
  'كل الأيام': 'Every day',
  'أوقات مخصصة للسيدات أو للرجال': 'Hours reserved for women or men',
  'خلال الوقت المخصص لا يُسمح بدخول الجنس الآخر. مثال: السيدات من 10 صباحاً إلى 2 ظهراً.': 'During reserved hours the other gender cannot enter. Example: women from 10 AM to 2 PM.',
  'إضافة وقت مخصص': 'Add reserved hours',
  'لا يدخل الجنس المخصص له وقت إلا في وقته': 'The gender with reserved hours enters only during them',
  'مثلاً: السيدات يدخلن فقط في أوقات السيدات': 'For example: women enter only during women\'s hours',
  'الانتهاء والديون': 'Expiry & debts',
  'أيام سماح بعد انتهاء الاشتراك': 'Grace days after expiry',
  'منع الدخول عند وجود مبلغ متأخر': 'Block entry when an amount is overdue',
  'وإلا يظهر تنبيه فقط': 'Otherwise only a warning is shown',
  'يُسمح بمتأخرات حتى': 'Overdue allowed up to',
  'متوسط مدة التمرين بالدقائق (لعدّ الموجودين الآن)': 'Average workout length in minutes (to count who is in now)',
  'وقت مخصص': 'Reserved hours',
  'من واتساب الجوال بلمسة (مجاني)': 'From phone WhatsApp with one tap (free)',
  'من تطبيق الرسائل بلمسة (مجاني)': 'From the Messages app with one tap (free)',
  'WhatsApp Cloud API الرسمي (آلي)': 'Official WhatsApp Cloud API (automatic)',
  'Twilio (آلي)': 'Twilio (automatic)',
  'مزوّد آخر برابط HTTP (آلي)': 'Other provider via HTTP link (automatic)',
  'من شريحة الجوال مباشرة (آلي، أندرويد)': 'Directly from the phone\'s SIM (automatic, Android)',
  'رقم للتجربة': 'Number for the test',
  'أُرسلت رسالة التجربة ✓': 'Test message sent ✓',
  'رابط المزوّد': 'Provider URL',
  'محتوى الطلب': 'Request body',
  'ترويسات (سطر لكل ترويسة)': 'Headers (one per line)',
  'نص يدل على النجاح (اختياري)': 'Success text (optional)',
  'المتغيرات: {phone} رقم دولي بدون +، {phone_plus} مع +، {phone_local} بالصفر المحلي، {message} نص الرسالة. يصلح لمعظم مزودي SMS وواتساب (UltraMsg، Green API، مزودي الرسائل المحليين...).': 'Variables: {phone} international without +, {phone_plus} with +, {phone_local} with local 0, {message} the text. Works with most SMS and WhatsApp providers (UltraMsg, Green API, local SMS providers...).',
  'تجهيز التذكيرات تلقائياً كل يوم': 'Prepare reminders automatically every day',
  'ساعات الإرسال': 'Sending hours',
  'لا تُرسل رسائل آلية خارج هذا الوقت': 'No automatic messages are sent outside these hours',
  'مجاني وبدون أي اشتراك: التطبيق يجهّز الرسالة ويفتح واتساب على رقم العضو، وأنت تضغط إرسال. مع «إرسال الكل» تُرسل عشرات التذكيرات في دقائق.': 'Free, no subscription: the app prepares the message and opens WhatsApp on the member\'s number, you tap send. With "Send all" you can send dozens of reminders in minutes.',
  'اسم القالب المعتمد (للتذكيرات)': 'Approved template name (for reminders)',
  'لغة القالب': 'Template language',
  'من Meta Business: أنشئ قالباً من فئة Utility بمتغيرين، مثل:\n«رسالة من النادي: {{1}}\n{{2}}\nشكراً لكم»\nالمتغير الأول = السطر الأول من الرسالة، والثاني = بقيتها. بدون قالب تُرسل الرسائل النصية فقط لمن راسلك خلال 24 ساعة.': 'In Meta Business, create a Utility template with two variables, e.g.:\n"Message from the gym: {{1}}\n{{2}}\nThank you"\nThe first variable = the first line of the message, the second = the rest. Without a template, text messages only reach people who messaged you in the last 24 hours.',
  'رقم واتساب المرسل': 'Sender WhatsApp number',
  'إرسال رسالة تجربة': 'Send a test message',
  'الرسائل النصية SMS': 'SMS text messages',
  'تُرسل الرسائل آلياً من شريحة هذا الجوال بتكلفة باقة الرسائل لديك. سيطلب أندرويد الإذن عند أول إرسال. يجب أن يبقى التطبيق مفتوحاً على جهاز الاستقبال.': 'Messages are sent automatically from this phone\'s SIM using your SMS bundle. Android asks for permission on the first send. The app must stay open on the reception device.',
  'رقم SMS المرسل': 'Sender SMS number',
  'إن فشل واتساب يُرسل SMS': 'Send SMS if WhatsApp fails',
  'التذكيرات الآلية': 'Automatic reminders',
  'جوال المالك (للملخص اليومي)': 'Owner\'s phone (for the daily summary)',
  'قبل الانتهاء بـ {d} يوم': '{d} days before expiry',
  'بعد الانتهاء بـ {d} يوم': '{d} days after expiry',
  'قبل موعد القسط بـ {d} يوم': '{d} days before the installment',
  'بعد التأخر بـ {d} يوم': '{d} days after it is late',
  'بعد غياب {d} يوم': 'After {d} days of absence',
  'عند بقاء {d} حصة': 'When {d} sessions are left',
  'الافتراضي': 'Default',
  'الأيام (افصل بفاصلة)': 'Days (comma separated)',
  'بدون (نقداً وبطاقة وتحويل فقط)': 'None (cash, card and transfer only)',
  'ميسّر Moyasar (السعودية)': 'Moyasar (Saudi Arabia)',
  'Tap Payments (الخليج)': 'Tap Payments (Gulf)',
  'رابط دفع ثابت (انستاباي، فوري، PayPal.me...)': 'Fixed payment link (InstaPay, Fawry, PayPal.me...)',
  'بيانات التحويل (تظهر في رسائل التذكير)': 'Transfer details (shown in reminders)',
  'انستاباي / فودافون كاش / STC Pay / IBAN': 'InstaPay / Vodafone Cash / STC Pay / IBAN',
  'للدفع: انستاباي gym@instapay أو فودافون كاش 010...': 'To pay: InstaPay gym@instapay or Vodafone Cash 010...',
  'بوابة الدفع': 'Payment gateway',
  'المفتاح السري (Secret key)': 'Secret key',
  'صفحة العودة بعد الدفع (اختياري)': 'Return page after payment (optional)',
  'ينشئ التطبيق رابط دفع لكل فاتورة ويرسله للعضو، ثم يتحقق تلقائياً من الدفع ويسجله. ابدأ بمفتاح الاختبار (test) وجرّب قبل التشغيل الفعلي.': 'The app creates a payment link for each invoice, sends it to the member, then checks and records the payment automatically. Start with a test key and try it before going live.',
  'الرابط': 'Link',
  'يمكن استخدام {amount} و {invoice} داخل الرابط. يؤكد الموظف استلام الدفع يدوياً من شاشة الفاتورة.': 'You can use {amount} and {invoice} in the link. Staff confirm receipt manually from the invoice screen.',
  'طلب الرقم السري عند فتح التطبيق': 'Ask for a PIN when opening the app',
  'كل موظف يدخل برقمه وتظهر له الشاشات حسب صلاحياته': 'Each staff member signs in with their PIN and sees screens according to their permissions',
  '{n} موظف لديهم رقم سري. أضف الأرقام من «الموظفون والمدربون».': '{n} staff members have a PIN. Add PINs in Staff & trainers.',
  'ضع رقماً سرياً للمالك أولاً من «الموظفون والمدربون» حتى لا تُقفل خارج التطبيق.': 'Set an owner PIN first in Staff & trainers so you don\'t get locked out.',
  'بياناتك محفوظة على هذا الجهاز. خذ نسخة احتياطية أسبوعياً وأرسلها لنفسك (Google Drive أو واتساب). يأخذ التطبيق أيضاً نسخة تلقائية يومية داخل الجوال.': 'Your data is saved on this device. Take a backup weekly and send it to yourself (Google Drive or WhatsApp). The app also takes an automatic daily backup on the phone.',
  'أخذ نسخة احتياطية ومشاركتها': 'Back up and share',
  '{m} عضو • {i} فاتورة': '{m} members • {i} invoices',
  'استرجاع من نسخة احتياطية': 'Restore from a backup',
  'يستبدل كل البيانات الحالية': 'Replaces all current data',
  'استبدال كل البيانات بالنسخة؟': 'Replace all data with the backup?',
  'تم الاسترجاع ✓': 'Restored ✓',
  'استيراد الأعضاء من Excel (CSV)': 'Import members from Excel (CSV)',
  'احفظ الجدول من Excel بصيغة CSV. الأعمدة: الاسم، الجوال، الجنس، الباقة، تاريخ الانتهاء، الرصيد': 'Save the sheet from Excel as CSV. Columns: name, phone, gender, plan, end date, balance',
  'نتيجة الاستيراد': 'Import result',
  'أعضاء: {n}': 'Members: {n}',
  'اشتراكات: {n}': 'Memberships: {n}',
  'تم تخطي: {n}': 'Skipped: {n}',
  'تصدير الأعضاء (CSV)': 'Export members (CSV)',
  'الجنس': 'Gender',
  'البداية': 'Start',
  'الانتهاء': 'End',
  'الرصيد': 'Balance',
  'تحميل بيانات تجريبية': 'Load demo data',
  'مسح كل البيانات': 'Erase all data',
  'اكتب «مسح» للتأكيد': 'Type "delete" to confirm',
  'لا توجد كوبونات': 'No coupons',
  'مثال: RAMADAN20 خصم 20% حتى نهاية الشهر': 'Example: RAMADAN20 gives 20% off until the end of the month',
  'استُخدم {n}': 'Used {n}',
  'الرمز': 'Code',
  'القيمة': 'Value',
  'أقصى عدد استخدامات (فارغ = بلا حد)': 'Max uses (empty = unlimited)',
  'صالح حتى': 'Valid until',
  'دائماً': 'Always',
  'الرئيسية': 'Home',
  'الأعضاء': 'Members',
  'الدخول': 'Check-in',
  'تم البيع ✓': 'Sold ✓',
  'عرض الفاتورة': 'View invoice',
  'المنتجات والمخزون': 'Products & stock',
  'على حساب العضو': 'On the member\'s account',
  'دفع {a}': 'Pay {a}',
  'ابحث أو امسح باركود المنتج': 'Search or scan a product barcode',
  'لا توجد منتجات': 'No products',
  'إضافة منتجات': 'Add products',
  'المتوفر: {n}': 'In stock: {n}',
  'التكلفة': 'Cost',
  'إضافة كمية لـ {p}': 'Add stock for {p}',
  '+ مخزون': '+ stock',
  'منتج جديد': 'New product',
  'سعر البيع': 'Sale price',
  'تتبّع المخزون': 'Track stock',
  'حد التنبيه': 'Alert level',
  'الفئة': 'Category',
  'الباركود': 'Barcode',
  'متاح للبيع': 'Available for sale',
  'موظف': 'Staff member',
  'له رقم سري': 'Has a PIN',
  'هذا الشهر: {n} جلسة، مستحق {a}': 'This month: {n} sessions, due {a}',
  'موظف جديد': 'New staff member',
  'الدور': 'Role',
  'رقم سري (4-6 أرقام)': 'PIN (4-6 digits)',
  'رقم سري جديد (اتركه فارغاً للإبقاء)': 'New PIN (leave empty to keep)',
  'مدرب (تدريب شخصي وحصص)': 'Trainer (personal training and classes)',
  'عمولة التدريب %': 'PT commission %',
  'أجر الجلسة': 'Pay per session',
  'نشط': 'Active',
  'الرقم السري 4 أرقام على الأقل': 'The PIN must be at least 4 digits',
  'يجب أن يبقى مالك واحد نشط على الأقل': 'At least one active owner must remain',
  'كل الصلاحيات': 'All permissions',
  'كل شيء عدا الإعدادات والموظفين': 'Everything except settings and staff',
  'الأعضاء، الدخول، البيع والتحصيل، الرسائل': 'Members, check-in, sales and collection, messages',
  'الدخول والحصص فقط': 'Check-in and classes only',
  'تأكيد': 'Confirm',
  'غداً': 'Tomorrow',
  'أمس': 'Yesterday',
  'بعد {n} يوم': 'In {n} days',
  'منذ {n} يوم': '{n} days ago',
  'تحصيل دفعة': 'Collect a payment',
  'المستحق: {a}': 'Due: {a}',
  'تم تسجيل الدفعة ✓': 'Payment recorded ✓',
  'إرسال إيصال للعضو؟': 'Send a receipt to the member?',
  'تذكير بالانتهاء': 'Expiry reminder',
  'تذكير بالمستحق': 'Payment reminder',
  'مرحباً {n}، نذكّرك بمبلغ {a} مستحق لدى {g}.\n{p}': 'Hi {n}, a reminder that {a} is due at {g}.\n{p}',
  'عرض خاص': 'Special offer',
  'مرحباً {n} 👋\nعرض خاص لك في {g}: خصم على التجديد هذا الأسبوع فقط! 💪': 'Hi {n} 👋\nA special offer for you at {g}: a renewal discount this week only! 💪',
  'رسالة إلى {n}': 'Message to {n}',
  'اكتب رسالتك...': 'Write your message...',
  'فيسبوك': 'Facebook',
  'إنستجرام': 'Instagram',
  'تيك توك': 'TikTok',
  'جوجل': 'Google',
  'صديق': 'A friend',
  'مرّ من أمام النادي': 'Walked by the gym',
  'إيجار': 'Rent',
  'رواتب': 'Salaries',
  'كهرباء ومياه': 'Electricity & water',
  'صيانة الأجهزة': 'Equipment maintenance',
  'إعلانات': 'Advertising',
  'مستلزمات': 'Supplies',
  'نظافة': 'Cleaning',
  'اسم العضو كاملاً': 'Member\'s full name',
  'الاسم الأول': 'First name',
  'تاريخ انتهاء الاشتراك': 'Membership end date',
  'الحصص المتبقية': 'Sessions left',
  'المتبقي على العضو': 'Member\'s balance',
  'تاريخ الاستحقاق': 'Due date',
  'رقم الفاتورة': 'Invoice number',
  'رابط أو بيانات الدفع': 'Payment link or details',
  'وقت الحصة': 'Class time',
  'ليست لديك صلاحية': 'You don\'t have permission',
  'لم يصل: {r} (عكس {n})': 'Not received: {r} (reverses {n})',
  'مجاني': 'Free',
  'التذكيرات التلقائية اليومية و«إرسال الكل»': 'Automatic daily reminders and "Send all"',
  'الرسائل الجماعية': 'Bulk messages',
  'التقسيط وتذكير الأقساط': 'Installments and installment reminders',
  'العروض والكوبونات': 'Offers and coupons',
  'الدفع بالمحافظ ورمز QR الموحد والمطابقة': 'Wallet payments, unified QR and reconciliation',
  'فواتير PDF والطباعة الحرارية': 'PDF invoices and thermal printing',
  'التقارير الكاملة والمصروفات': 'Full reports and expenses',
  'قياسات الجسم': 'Body measurements',
  'الاستيراد والتصدير Excel': 'Excel import and export',
  'الموظفون والصلاحيات (حتى 5)': 'Staff and permissions (up to 5)',
  'رمز QR للفاتورة الضريبية': 'Tax invoice QR code',
  'إرسال آلي كامل (واتساب API، SMS من الشريحة)': 'Fully automatic sending (WhatsApp API, SMS from SIM)',
  'بوابات الدفع الإلكتروني': 'Online payment gateways',
  'التجديد شبه التلقائي': 'Semi-automatic renewal',
  'التدريب الشخصي وعمولات المدربين': 'Personal training and trainer commissions',
  'سجل العمليات وموظفون بلا حد': 'Activity log and unlimited staff',
  'الملخص اليومي للمالك': 'Daily owner summary',
  'تجربة Pro — متبقٍ {n} يوم': 'Pro trial — {n} days left',
  '{t} — دائمة': '{t} — lifetime',
  '{t} — حتى {d}': '{t} — until {d}',
  'انتهى اشتراك {t} — تعمل الآن المزايا المجانية': '{t} subscription ended — free features are active',
  'النسخة المجانية': 'Free version',
  'صيغة مفتاح التفعيل غير صحيحة. انسخه كاملاً كما وصلك': 'Invalid activation key format. Copy it exactly as you received it',
  'مفتاح التفعيل تالف': 'The activation key is damaged',
  'مفتاح التفعيل غير صالح': 'Invalid activation key',
  'مفتاح التفعيل لجهاز آخر': 'The activation key is for another device',
  '«{f}» متاحة في نسخة {t}. رقِّ النسخة من الإعدادات › الترخيص': '"{f}" is available in {t}. Upgrade from Settings › License',
  'هذا المفتاح لجهاز آخر ({d}). رمز هذا الجهاز: {m}': 'This key is for another device ({d}). This device\'s code: {m}',
  'هذا المفتاح منتهي منذ {d}': 'This key expired on {d}',
  'النسخة المجانية تتسع لـ {n} عضواً فعّالاً. رقِّ إلى Plus لأعضاء بلا حد': 'The free version allows {n} active members. Upgrade to Plus for unlimited members',
  'فاتورة تجديد: يتجدد الاشتراك تلقائياً عند اكتمال الدفع': 'Renewal invoice: the membership renews automatically when fully paid',
  'ادفع': 'Pay',
  'نُسخ نص الرسالة ورقم الجوال — أرسلها من جوالك': 'Message text and phone copied — send it from your phone',
  'حفظ الملف': 'Save file',
  'المطابقة': 'Reconciliation',
  'قارن هذه المجاميع مع كشف كل محفظة أو حساب بنكي': 'Compare these totals with each wallet or bank statement',
  'لا دفعات في هذه الفترة': 'No payments in this period',
  '{n} عملية': '{n} transactions',
  '{n} بانتظار التأكد': '{n} awaiting confirmation',
  'بانتظار التأكد من الوصول ({n})': 'Awaiting confirmation of receipt ({n})',
  'كل التحويلات مؤكدة ✓': 'All transfers confirmed ✓',
  'لم يصل': 'Not received',
  'المبلغ لم يصل؟ سيعود ديناً على العضو': 'Not received? It will become the member\'s debt again',
  'عُكست الدفعة': 'Payment reversed',
  'وصل': 'Received',
  'تم التأكيد ✓': 'Confirmed ✓',
  'فاتورة تجديد': 'Renewal invoice',
  'يتجدد الاشتراك تلقائياً عند اكتمال الدفع': 'The membership renews automatically when fully paid',
  'بانتظار التأكد': 'Awaiting confirmation',
  'طلب دفع: صورة رمز QR + المبلغ': 'Payment request: QR image + amount',
  'مرحباً {n}، المطلوب {a} (فاتورة {i}). امسح الرمز من تطبيق البنك أو المحفظة، ثم أرسل لنا رقم العملية. شكراً 🙏': 'Hi {n}, the amount due is {a} (invoice {i}). Scan the code from your bank or wallet app, then send us the transaction number. Thank you 🙏',
  'مرّر البطاقة على قارئ الباركود': 'Scan your card on the barcode reader',
  'شهرياً': 'monthly',
  'سنوياً': 'yearly',
  'مدى الحياة': 'lifetime',
  'تم التفعيل ✓ {l}': 'Activated ✓ {l}',
  'طلب تفعيل {t}': 'Request {t} activation',
  'حوّلت عبر': 'Paid via',
  'رقم العملية / الحوالة': 'Transaction / transfer number',
  'سيفتح واتساب برسالة جاهزة فيها رمز جهازك. يصلك مفتاح التفعيل بعد التأكد من التحويل.': 'WhatsApp opens with a ready message including your device code. You\'ll receive the activation key once the transfer is confirmed.',
  'إرسال الطلب': 'Send request',
  'طلب تفعيل نادي جيم': 'Nadi Gym activation request',
  'رمز الجهاز': 'Device code',
  'الترخيص والباقات': 'License & plans',
  'رمز الجهاز:': 'Device code:',
  'نسخ': 'Copy',
  'نُسخ رمز الجهاز': 'Device code copied',
  'طريقة الشراء': 'How to buy',
  '1. حوّل ثمن الباقة إلى أحد الحسابات (أو امسح الرمز الموحد من أي تطبيق بنكي أو محفظة):': '1. Transfer the price to one of these accounts (or scan the unified QR from any bank or wallet app):',
  'نُسخ': 'Copied',
  '2. اضغط «اشترِ» على الباقة واكتب رقم العملية؛ يُرسل الطلب بواتساب مع رمز جهازك.': '2. Tap "Buy" on the plan and enter the transaction number; the request is sent via WhatsApp with your device code.',
  '3. الصق مفتاح التفعيل الذي يصلك هنا:': '3. Paste the activation key you receive here:',
  'تفعيل': 'Activate',
  'بياناتك تبقى متاحة دائماً: عند انتهاء الاشتراك يعود التطبيق للنسخة المجانية ولا يُحذف شيء.': 'Your data always stays available: when a subscription ends, the app returns to the free version and nothing is deleted.',
  'إزالة مفتاح التفعيل من هذا الجهاز؟': 'Remove the activation key from this device?',
  'إزالة المفتاح': 'Remove key',
  'آخر تحقق': 'Last check',
  'حتى {n} عضو فعّال': 'Up to {n} active members',
  'الاشتراكات والتجديد والتجميد': 'Memberships, renewals and freezes',
  'الدخول بمسح QR أو البحث': 'Check-in by QR scan or search',
  'الدفع النقدي والبطاقة والمحفظة': 'Cash, card and wallet payments',
  'الفواتير وإرسالها بواتساب': 'Invoices sent via WhatsApp',
  'رسائل فردية بواتساب و SMS': 'Individual WhatsApp and SMS messages',
  'النسخ الاحتياطي': 'Backups',
  'كل مزايا المجاني وأعضاء بلا حد': 'Everything in Free, plus unlimited members',
  'كل مزايا Plus': 'Everything in Plus',
  'الحالية': 'Current',
  'مجاناً دائماً': 'Free forever',
  'اشترِ {t}': 'Buy {t}',
  'إرسال طلب تجديد': 'Send renewal request',
  'باقة الاشتراك الحالي غير متاحة للبيع': 'The current membership\'s plan is not available for sale',
  'متاحة في نسخة {t}': 'Available in {t}',
  'عرض الباقات': 'See plans',
  'تجديد تلقائي': 'Auto-renewal',
  'قبل الانتهاء بأيام تُجهّز فاتورة التجديد وتُرسل له مع رمز الدفع، ويتجدد عند الدفع': 'A few days before expiry, a renewal invoice is prepared and sent with the payment QR; it renews on payment',
  'ترقية': 'Upgrade',
  'خصم {v}%': '{v}% off',
  'خصم {v}': '{v} off',
  'بسعر {v}': 'For {v}',
  '+{n} يوم مجاناً': '+{n} free days',
  'للأعضاء الجدد': 'New members',
  'مفتوح': 'open',
  'العروض': 'Offers',
  'الكوبونات': 'Coupons',
  'عرض': 'Offer',
  'لا توجد عروض': 'No offers',
  'مثال: «عرض الصيف» خصم 20% على 3 و6 أشهر حتى نهاية أغسطس، أو «3 أشهر + 15 يوماً هدية». يظهر العرض تلقائياً للموظف عند البيع والتجديد.': 'Example: "Summer offer" 20% off 3 and 6 months until the end of August, or "3 months + 15 free days". Offers appear automatically when selling and renewing.',
  'عرض جديد': 'New offer',
  'تعديل العرض': 'Edit offer',
  'اسم العرض': 'Offer name',
  'عرض رمضان': 'Ramadan offer',
  'خصم %': '% off',
  'خصم مبلغ': 'Amount off',
  'سعر خاص': 'Special price',
  'النسبة %': 'Percent %',
  'السعر الخاص': 'Special price',
  'أيام مجانية إضافية': 'Extra free days',
  'الباقات المشمولة (بدون اختيار = كل الباقات)': 'Included plans (none selected = all plans)',
  'للأعضاء الجدد فقط': 'New members only',
  'حسابات استلام الدفع': 'Payment receiving accounts',
  'حساب': 'Account',
  'أضف المحافظ والحسابات التي يحوّل لها الأعضاء، ولكل حساب رمز QR الموحد (iBuraq QR Quick) من تطبيق بنكك أو محفظتك: يظهر للعضو ليمسحه من أي تطبيق بنكي أو محفظة، ويُرسل مع طلبات الدفع والتجديد، ويُطبع على الفاتورة.': 'Add the wallets and accounts members pay into, each with its unified QR code (iBuraq QR Quick) from your bank or wallet app: members scan it from any bank or wallet app, it is sent with payment and renewal requests, and printed on invoices.',
  'لا توجد حسابات': 'No accounts',
  '✓ رمز QR': '✓ QR code',
  'حساب استلام جديد': 'New receiving account',
  'محفظة': 'Wallet',
  'بنك / iBuraq': 'Bank / iBuraq',
  'رقم المحفظة': 'Wallet number',
  'رقم الحساب / IBAN / المعرّف': 'Account number / IBAN / alias',
  'اسم صاحب الحساب': 'Account holder',
  'رمز QR الموحد لهذا الحساب': 'Unified QR code for this account',
  'مسح بالكاميرا': 'Scan with camera',
  'من صورة': 'From image',
  'لم يُعثر على رمز QR في الصورة': 'No QR code found in the image',
  'محتوى الرمز (أو الصقه هنا)': 'Code content (or paste it here)',
  'من تطبيق البنك أو المحفظة: افتح «استلام» أو «QR Quick» واعرض رمز حسابك بدون مبلغ، ثم امسحه بالكاميرا أو احفظه صورة واختره من «من صورة».': 'In your bank or wallet app open "Receive" or "QR Quick" and show your account code without an amount, then scan it with the camera or save it as an image and pick it with "From image".',
  'امسح رمز QR': 'Scan QR code',
  'حسب الحساب / المحفظة': 'By account / wallet',
  'خصم {a}': '{a} off',
  'حتى {d}': 'until {d}',
  'تطبيق العرض الساري': 'Apply the current offer',
  'حسابات الاستلام ورمز QR الموحد': 'Receiving accounts and unified QR',
  'جوال باي، بال باي، البنوك، iBuraq — {n} حساب': 'Jawwal Pay, PalPay, banks, iBuraq — {n} accounts',
  'نص بيانات الدفع (اختياري)': 'Payment details text (optional)',
  'فارغ = يُكتب تلقائياً من حسابات الاستلام': 'Empty = built automatically from receiving accounts',
  'نسختك تسمح بـ {n} موظف. رقِّ النسخة لإضافة المزيد': 'Your version allows {n} staff. Upgrade to add more',
  'اعرض رمز QR ليدفع العضو': 'Show the QR for the member to pay',
  'تأكدت من وصول المبلغ إلى الحساب': 'I confirmed the money arrived in the account',
  'وإلا تبقى الدفعة في «المطابقة» حتى تتأكد': 'Otherwise the payment stays in "Reconciliation" until confirmed',
  'رقم العملية (اختياري)': 'Transaction number (optional)',
  'امسح الرمز من تطبيق البنك أو المحفظة (iBuraq) وادفع المبلغ': 'Scan the code from your bank or wallet app (iBuraq) and pay the amount',
  'امسح الرمز من أي تطبيق بنكي أو محفظة': 'Scan with any bank or wallet app',
  'ميزة مدفوعة': 'Paid feature',
  'لاحقاً': 'Later',
  // المزامنة السحابية
  'غير مفعلة': 'Off',
  'متزامن': 'Synced',
  'جارٍ المزامنة...': 'Syncing...',
  '{n} تعديل بانتظار الرفع': '{n} changes waiting to upload',
  'بدون نت — {n} تعديل محفوظ على الجهاز': 'Offline — {n} changes saved on this device',
  'خطأ في المزامنة': 'Sync error',
  'متوقفة (الترخيص)': 'Paused (license)',
  'لم تتم بعد': 'Not yet',
  'المزامنة السحابية': 'Cloud sync',
  'كل شيء يُحفظ على هذا الجهاز أولاً، والتطبيق يعمل بالكامل بدون إنترنت. عند توفر النت تُرفع تعديلاتك وتصل تعديلات أجهزة النادي الأخرى تلقائياً، وتبقى نسخة من بياناتك على السحابة إن ضاع الجهاز.': 'Everything is saved on this device first, and the app works fully offline. When the internet is available, your changes upload and changes from the gym\'s other devices arrive automatically, and a copy of your data stays in the cloud in case the device is lost.',
  'أول جهاز في النادي': 'First device of the gym',
  'يرفع بيانات هذا الجهاز إلى السحابة ويعطيك رمزاً لربط باقي الأجهزة.': 'Uploads this device\'s data to the cloud and gives you a code to link your other devices.',
  'تفعيل المزامنة على هذا الجهاز': 'Turn on sync on this device',
  'تم رفع بيانات النادي ✓': 'Gym data uploaded ✓',
  'ربط بجهاز النادي': 'Link to the gym\'s device',
  'على الجهاز الأول افتح: الإعدادات › المزامنة السحابية › إضافة جهاز، ثم امسح الرمز من هنا.': 'On the first device open Settings › Cloud sync › Add device, then scan the code from here.',
  'آخر مزامنة: {t}': 'Last sync: {t}',
  'الأجهزة: {n} من {l} • هذا الجهاز رقم {s}': 'Devices: {n} of {l} • this is device {s}',
  'مزامنة الآن': 'Sync now',
  'إضافة جهاز': 'Add device',
  'اعرض رمز الربط وامسحه من الجهاز الجديد': 'Show the link code and scan it from the new device',
  'الجهاز الرئيسي': 'Main device',
  'يجهّز التذكيرات الآلية ويرسلها ويفحص روابط الدفع. فعّله على جهاز واحد فقط (جهاز الاستقبال) حتى لا تتكرر الرسائل.': 'Prepares and sends automatic reminders and checks payment links. Turn it on for one device only (the front desk) so messages are not duplicated.',
  'إيقاف المزامنة على هذا الجهاز': 'Stop sync on this device',
  'تبقى البيانات على هذا الجهاز وعلى السحابة. التعديلات التي لم تُرفع بعد ستبقى هنا فقط.': 'Data stays on this device and in the cloud. Changes not uploaded yet will stay here only.',
  'إيقاف المزامنة؟': 'Stop sync?',
  'إيقاف': 'Stop',
  'رمز ربط جهاز جديد': 'New device link code',
  'من يملك هذا الرمز يصل لبيانات النادي. لا ترسله إلا لأجهزة ناديك.': 'Anyone with this code can access the gym\'s data. Only share it with your gym\'s devices.',
  'نسخ الرمز': 'Copy code',
  'خادم المزامنة': 'Sync server',
  'أدخل عنوان مشروع Supabase ومفتاح anon (بعد تنفيذ ملف server/supabase_sync.sql). يُعطى لك مع النسخة المدفوعة.': 'Enter the Supabase project URL and anon key (after running server/supabase_sync.sql). Provided with the paid version.',
  'استبدال بيانات هذا الجهاز؟': 'Replace this device\'s data?',
  'ستُحذف البيانات الموجودة على هذا الجهاز وتُستبدل ببيانات النادي من السحابة.': 'The data on this device will be deleted and replaced with the gym\'s data from the cloud.',
  'ربط': 'Link',
  'تم ربط الجهاز واستلام بيانات النادي ✓': 'Device linked and gym data received ✓',
  'مسح رمز الربط': 'Scan link code',
  'لصق الرمز': 'Paste code',
  'رمز الربط': 'Link code',
  'ناديك مسجّل على جهاز آخر؟ اربط هذا الجهاز': 'Gym already on another device? Link this device',
  'بياناتك تُحفظ على هذا الجهاز ويعمل التطبيق كاملاً بدون إنترنت. خذ نسخة احتياطية بانتظام، أو فعّل المزامنة السحابية.': 'Your data is saved on this device and the app works fully offline. Take regular backups, or turn on cloud sync.',
  'عدة أجهزة لنفس النادي، ونسخة على السحابة، مع العمل بدون نت': 'Several devices for one gym and a cloud copy, while working offline',
  'رمز الربط غير صحيح أو أُلغي': 'The link code is wrong or was revoked',
  'تجاوزت عدد الأجهزة المسموح لهذا النادي': 'This gym has reached its device limit',
  'رفض الخادم المزامنة: {c}': 'The server refused to sync: {c}',
  'رمز الربط غير صحيح': 'Invalid link code',
  'أدخل عنوان خادم المزامنة ومفتاحه': 'Enter the sync server URL and key',
  'عدد الأجهزة المتزامنة ({n}) أكبر من المسموح في نسختك ({l}). رقِّ إلى Pro للمزامنة حتى {p} أجهزة': 'Synced devices ({n}) exceed your plan\'s limit ({l}). Upgrade to Pro to sync up to {p} devices',
  'المزامنة السحابية متاحة في نسخة Plus. بياناتك محفوظة على الجهاز': 'Cloud sync is available in Plus. Your data is safe on this device',
  'لا يوجد اتصال بالإنترنت. التطبيق يعمل عادياً وستتم المزامنة عند عودة النت': 'No internet connection. The app works normally and will sync when the internet is back',
  'المزامنة والنسخ السحابي (جهازان)': 'Cloud sync and backup (2 devices)',
  'مزامنة حتى {n} أجهزة': 'Sync up to {n} devices',
  // التحقق من القيم
  'اكتب اسم العرض': 'Enter the offer name',
  'القيم لا تكون سالبة': 'Values cannot be negative',
  'النسبة لا تزيد عن 100%': 'Percentage cannot exceed 100%',
  'اكتب السعر الخاص': 'Enter the special price',
  'حدّد خصماً أو أياماً مجانية': 'Set a discount or free days',
  'تاريخ النهاية قبل البداية': 'End date is before start date',
  'السعر والرسوم لا تكون سالبة': 'Price and fees cannot be negative',
  'مدة الباقة يجب أن تكون 1 أو أكثر': 'Plan duration must be 1 or more',
  'عدد الحصص يجب أن يكون 1 أو أكثر': 'Number of sessions must be 1 or more',
  'أيام ومرات التجميد لا تكون سالبة': 'Freeze days and times cannot be negative',
  'وقت البداية والنهاية متساويان': 'Start and end times are the same',
  'السعر والتكلفة والكمية لا تكون سالبة': 'Price, cost and quantity cannot be negative',
  'ضريبة القيمة المضافة': 'VAT',
  'اكتب اسم الحصة': 'Enter the class name',
  'السعة يجب أن تكون 1 أو أكثر': 'Capacity must be 1 or more',
  'مدة الحصة بين 5 و600 دقيقة': 'Class duration must be between 5 and 600 minutes',
  'اكتب رمز الكوبون': 'Enter the coupon code',
  'هذا الرمز مستخدم لكوبون آخر': 'This code is used by another coupon',
  'اكتب قيمة الخصم': 'Enter the discount value',
  'عدد الاستخدامات غير صحيح': 'Invalid number of uses',
  'الخصم لا يكون سالباً': 'Discount cannot be negative',
  'نسبة الخصم لا تزيد عن 100%': 'Discount cannot exceed 100%',
  'المبلغ المدفوع لا يكون سالباً': 'Paid amount cannot be negative',
  'كل قسط يجب أن يكون أكبر من صفر': 'Each installment must be more than zero',
  'تاريخ النهاية قبل بداية الاشتراك ({d})': 'End date is before the membership start ({d})',
  'الحصص المستخدمة بين 0 و{t}': 'Used sessions must be between 0 and {t}',
};
